### ISSUE TITLE
Dealing with multiple sessions

### ISSUE THREAD

**Issue by malywladek** [nencki-lobi/bids-flow#1]
Currently we do not separate subsequent sessions of the same subject but overwrites previous one. One should pay attention to use unique subjects ids.

**Comment by mslw** [comment]
For the ongoing project affected by this issue (which has two sessions with same subject names but different sets of tasks) we can mitigate it by trying to parse task names & run numbers from the dicom series name. I can do it this week.

To solve it in general - I think we would need to check if a given subject is already present in the reports folder and change subject's name during conversion?

**Comment by malywladek** [comment]
Good job! Now we can deal with different fMRI sessions of the same subjects. We can leave other cases for further discussion and/or pay attention to unique ids for longitudinal studies.

**Comment by bkossows** [comment]
It looks like we still need to find a workaround for multiple sessions. I'd opt for sub-XXX/ses-DATE structure. In dicominfo.tsv there is already a 'date' field available.
